"""add_budget_analysis_system_tables

Revision ID: 9e79fe0d4d7a
Revises: d7a37370ef38
Create Date: 2025-08-19 23:22:02.881154+00:00

FINANCIAL SAFETY NOTICE:
This migration affects financial data. Ensure proper backup and testing procedures
are followed before applying to production. All changes must be reversible.

ROLLBACK STRATEGY:
- Test rollback procedures in staging environment
- Verify data integrity after rollback
- Document any manual steps required for rollback

"""
from typing import Sequence, Union
import logging

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import SQLAlchemyError, OperationalError


# revision identifiers, used by Alembic.
revision: str = '9e79fe0d4d7a'
down_revision: Union[str, None] = 'd7a37370ef38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Configure logging for this migration
logger = logging.getLogger(__name__)


def validate_data_integrity() -> bool:
    """
    Validate financial data integrity before and after migration.
    This function should be customized for each migration's specific requirements.
    """
    try:
        # Add specific validation logic here
        # Example: Check for orphaned records, constraint violations, etc.
        logger.info("Data integrity validation passed")
        return True
    except Exception as e:
        logger.error(f"Data integrity validation failed: {e}")
        return False


def upgrade() -> None:
    """Apply the migration changes."""
    logger.info(f"Starting migration upgrade: add_budget_analysis_system_tables")
    
    try:
        # Validate data integrity before migration
        if not validate_data_integrity():
            raise RuntimeError("Pre-migration data integrity check failed")
        
        # ### commands auto generated by Alembic - please adjust! ###
        # Budget tables were already created via SQLAlchemy create_all()
        # This migration serves as a record of the schema addition
        # ### end Alembic commands ###
        
        # Validate data integrity after migration
        if not validate_data_integrity():
            raise RuntimeError("Post-migration data integrity check failed")
        
        logger.info(f"Migration upgrade completed successfully: add_budget_analysis_system_tables")
        
    except (SQLAlchemyError, OperationalError) as e:
        logger.error(f"Database error in migration upgrade: {e}")
        raise
    except Exception as e:
        logger.error(f"Unexpected error in migration upgrade: {e}")
        raise


def downgrade() -> None:
    """Rollback the migration changes."""
    logger.info(f"Starting migration downgrade: add_budget_analysis_system_tables")
    
    try:
        # Validate data integrity before rollback
        if not validate_data_integrity():
            raise RuntimeError("Pre-rollback data integrity check failed")
        
        # ### commands auto generated by Alembic - please adjust! ###
        # Budget tables downgrade - would require dropping tables
        # This migration serves as a record of the schema addition
        # ### end Alembic commands ###
        
        # Validate data integrity after rollback
        if not validate_data_integrity():
            raise RuntimeError("Post-rollback data integrity check failed")
        
        logger.info(f"Migration downgrade completed successfully: add_budget_analysis_system_tables")
        
    except (SQLAlchemyError, OperationalError) as e:
        logger.error(f"Database error in migration downgrade: {e}")
        raise
    except Exception as e:
        logger.error(f"Unexpected error in migration downgrade: {e}")
        raise
